"""add_graph_checkpoints

Revision ID: 7e1aaa26ef7f
Revises: 138aa622bdbc
Create Date: 2026-06-10 07:09:08.392906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e1aaa26ef7f'
down_revision: Union[str, Sequence[str], None] = '138aa622bdbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_checkpoints',
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('checkpoint_ns', sa.String(length=100), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=100), nullable=False),
    sa.Column('parent_checkpoint_id', sa.String(length=100), nullable=True),
    sa.Column('checkpoint_blob', sa.LargeBinary(), nullable=False),
    sa.Column('metadata_blob', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id'),
    schema='ai'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graph_checkpoints', schema='ai')
    # ### end Alembic commands ###
