"""add_checkpoint_format

Revision ID: dcc825b96682
Revises: 7e1aaa26ef7f
Create Date: 2026-06-10 07:12:50.643664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc825b96682'
down_revision: Union[str, Sequence[str], None] = '7e1aaa26ef7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graph_checkpoints', sa.Column('checkpoint_format', sa.String(length=50), nullable=False), schema='ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('graph_checkpoints', 'checkpoint_format', schema='ai')
    # ### end Alembic commands ###
